# Generated by Django 4.2.3 on 2023-07-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('message_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id сообщения')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Телеграм id')),
                ('first_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Псевдоним')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('message_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id сообщения')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo_url', models.CharField(blank=True, max_length=80, null=True, verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Ответ бота',
                'verbose_name_plural': 'Ответы бота',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='MessageResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.message')),
                ('response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.response')),
            ],
            options={
                'verbose_name': 'Сообщение - ответ',
                'verbose_name_plural': 'Сообщении - ответы',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.profile'),
        ),
    ]
