# Generated by Django 4.2.3 on 2023-07-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Телеграм id')),
                ('first_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Псевдоним')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('message_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id сообщения')),
                ('text', models.TextField(verbose_name='Текст')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.profile')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('message_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id сообщения')),
                ('response', models.TextField(verbose_name='Текст')),
                ('photo_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на изображение')),
                ('from_command', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.message')),
            ],
            options={
                'verbose_name': 'Ответ бота',
                'verbose_name_plural': 'Ответы бота',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
    ]
