# Generated by Django 4.2.3 on 2023-07-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageresponse',
            options={'ordering': ('-created_at', '-updated_at'), 'verbose_name': 'Сообщение - ответ', 'verbose_name_plural': 'Сообщении - ответы'},
        ),
        migrations.AddField(
            model_name='messageresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='messageresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
