# Generated by Django 4.2.3 on 2023-07-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_avatar_url_alter_message_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(default='https://i.ibb.co/y68FLSn/anonymous.png', max_length=80, verbose_name='Аватар'),
        ),
    ]
