# Generated by Django 4.2.3 on 2023-07-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='photo_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
